// <auto-generated />
using System;
using MediaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190923090206_NewDb")]
    partial class NewDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaWeb.Domain.Film.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschrijving");

                    b.Property<byte[]>("Foto");

                    b.Property<int>("Lengte");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.HasKey("Id");

                    b.ToTable("FilmGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Comedy"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Animation"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmGezienStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("FilmGezienStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Niet gezien"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Wil ik nooit zien"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Gezien"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Wil ik zien"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("FilmPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmRatingReview", b =>
                {
                    b.Property<int>("FilmId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("FilmId", "UserId");

                    b.ToTable("FilmRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmRegisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Naam");

                    b.HasKey("Id");

                    b.ToTable("FilmRegisseur");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.GenreFilm", b =>
                {
                    b.Property<int>("FilmId");

                    b.Property<int>("GenreId");

                    b.HasKey("FilmId", "GenreId");

                    b.ToTable("GenreFilm");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.RegisseurFilm", b =>
                {
                    b.Property<int>("FilmId");

                    b.Property<int>("RegisseurId");

                    b.HasKey("FilmId", "RegisseurId");

                    b.ToTable("RegisseurFilm");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmFavourite", b =>
                {
                    b.Property<int>("FilmId");

                    b.Property<string>("UserId");

                    b.HasKey("FilmId", "UserId");

                    b.ToTable("UserFilmFavourite");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmGezienStatus", b =>
                {
                    b.Property<int>("FilmId");

                    b.Property<string>("UserId");

                    b.Property<int>("StatusId");

                    b.HasKey("FilmId", "UserId");

                    b.ToTable("UserFilmGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmPlaylist", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("PlaylistId");

                    b.Property<int>("FilmId");

                    b.HasKey("UserId", "PlaylistId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("UserFilmPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.GenreMuziek", b =>
                {
                    b.Property<int>("GenreId");

                    b.Property<int>("MuziekId");

                    b.Property<int?>("NummerId");

                    b.HasKey("GenreId", "MuziekId");

                    b.HasIndex("NummerId");

                    b.ToTable("GenreMuziek");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("AlbumArt");

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("MuziekAlbum");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekArtiest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam");

                    b.HasKey("Id");

                    b.ToTable("MuziekArtiest");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekGeluisterdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("MuziekGeluisterdStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Niet geluisterd"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Wil ik niet naar luisteren"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Geluisterd"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Wil ik naar luisteren"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.HasKey("Id");

                    b.ToTable("MuziekGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Jazz"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Metal"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Pop"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Hip-hop"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Rap"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Alternative"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Instrumental"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Orchestral"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Punk"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("MuziekPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekRatingReview", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("MuziekId");

                    b.Property<int?>("NummerId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("UserId", "MuziekId");

                    b.HasIndex("NummerId");

                    b.ToTable("MuziekRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.Nummer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<int>("ArtiestId");

                    b.Property<int>("Lengte");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtiestId");

                    b.ToTable("Nummer");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekFavourite", b =>
                {
                    b.Property<int>("MuziekId");

                    b.Property<string>("UserId");

                    b.Property<int?>("NummerId");

                    b.HasKey("MuziekId", "UserId");

                    b.HasIndex("NummerId");

                    b.ToTable("UserMuziekFavourite");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekGeluisterdStatus", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("MuziekId");

                    b.Property<int>("MuziekGeluisterdStatusId");

                    b.Property<int?>("NummerId");

                    b.HasKey("UserId", "MuziekId");

                    b.HasIndex("NummerId");

                    b.ToTable("UserMuziekGeluisterdStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekPlaylist", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("PlaylistId");

                    b.Property<int>("MuziekId");

                    b.Property<int?>("NummerId");

                    b.HasKey("UserId", "PlaylistId", "MuziekId");

                    b.HasIndex("NummerId");

                    b.ToTable("UserMuziekPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.GenrePodcast", b =>
                {
                    b.Property<int>("GenreId");

                    b.Property<int>("PodcastId");

                    b.HasKey("GenreId", "PodcastId");

                    b.HasIndex("PodcastId");

                    b.ToTable("GenrePodcast");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.Podcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Auteur");

                    b.Property<byte[]>("PodcastArt");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("Podcast");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Lengte");

                    b.Property<int>("PodcastId");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.HasIndex("PodcastId");

                    b.ToTable("PodcastEpisode");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastGeluisterdStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("PodcastGeluisterdStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Niet geluisterd"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Wil ik niet naar luisteren"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Geluisterd"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Wil ik naar luisteren"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.HasKey("Id");

                    b.ToTable("PodcastGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Science"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Educational"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "News"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Sport"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("PodcastPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastRatingReview", b =>
                {
                    b.Property<int>("PodcastEpisodeId");

                    b.Property<string>("UserId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("PodcastEpisodeId", "UserId");

                    b.ToTable("PodcastRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastFavourite", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("PodcastEpisodeId");

                    b.HasKey("UserId", "PodcastEpisodeId");

                    b.HasIndex("PodcastEpisodeId");

                    b.ToTable("UserPodcastFavourite");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastGeluisterdStatus", b =>
                {
                    b.Property<int>("PodcastId");

                    b.Property<string>("UserId");

                    b.Property<int>("StatusId");

                    b.HasKey("PodcastId", "UserId");

                    b.ToTable("UserPodcastGeluisterdStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastPlaylist", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("PlaylistId");

                    b.Property<int>("PodcastEpisodeId");

                    b.HasKey("UserId", "PlaylistId", "PodcastEpisodeId");

                    b.HasIndex("PodcastEpisodeId");

                    b.ToTable("UserPodcastPlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.GenreSerie", b =>
                {
                    b.Property<int>("GenreId");

                    b.Property<int>("SerieId");

                    b.HasKey("GenreId", "SerieId");

                    b.HasIndex("SerieId");

                    b.ToTable("GenreSerie");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("SerieArt");

                    b.Property<string>("Titel");

                    b.Property<bool>("Zichtbaar");

                    b.HasKey("Id");

                    b.ToTable("Serie");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Lengte");

                    b.Property<int>("SerieId");

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("SerieEpisode");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Genre");

                    b.HasKey("Id");

                    b.ToTable("SerieGenre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Thriller"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Comedy"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Animation"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieGezienStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("SerieGezienStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Niet gezien"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Wil ik niet zien"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Gezien"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Wil ik zien"
                        });
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SeriePlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Titel");

                    b.HasKey("Id");

                    b.ToTable("SeriePlaylist");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieRatingReview", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("SerieEpisodeId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("UserId", "SerieEpisodeId");

                    b.HasIndex("SerieEpisodeId");

                    b.ToTable("SerieRatingReview");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSerieFavourite", b =>
                {
                    b.Property<int>("SerieEpisodeId");

                    b.Property<string>("UserId");

                    b.HasKey("SerieEpisodeId", "UserId");

                    b.ToTable("UserSerieFavourite");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSerieGezienStatus", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("SerieId");

                    b.Property<int>("StatusId");

                    b.HasKey("UserId", "SerieId");

                    b.ToTable("UserSerieGezienStatus");
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSeriePlaylist", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<int>("SerieEpisodeId");

                    b.Property<int>("PlaylistId");

                    b.HasKey("UserId", "SerieEpisodeId", "PlaylistId");

                    b.HasIndex("SerieEpisodeId");

                    b.ToTable("UserSeriePlaylist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.FilmRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("RatingReviews")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.GenreFilm", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("Genres")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.RegisseurFilm", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("Regisseurs")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmFavourite", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("Favourites")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmGezienStatus", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("FilmGezienStatuses")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Film.UserFilmPlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Film.Film")
                        .WithMany("Playlists")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.GenreMuziek", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.Nummer")
                        .WithMany("Genres")
                        .HasForeignKey("NummerId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.MuziekRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.Nummer")
                        .WithMany("RatingReviews")
                        .HasForeignKey("NummerId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.Nummer", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.MuziekAlbum", "Album")
                        .WithMany("Nummer")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MediaWeb.Domain.Muziek.MuziekArtiest", "Artiest")
                        .WithMany("Nummer")
                        .HasForeignKey("ArtiestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekFavourite", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.Nummer")
                        .WithMany("Favourites")
                        .HasForeignKey("NummerId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekGeluisterdStatus", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.Nummer")
                        .WithMany("GeluisterdStatus")
                        .HasForeignKey("NummerId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Muziek.UserMuziekPlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Muziek.Nummer")
                        .WithMany("Playlists")
                        .HasForeignKey("NummerId");
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.GenrePodcast", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.Podcast")
                        .WithMany("Genres")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastEpisode", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.PodcastRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.PodcastEpisode")
                        .WithMany("RatingReviews")
                        .HasForeignKey("PodcastEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastFavourite", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.PodcastEpisode")
                        .WithMany("Favourites")
                        .HasForeignKey("PodcastEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Podcast.UserPodcastPlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Podcast.PodcastEpisode")
                        .WithMany("Playlists")
                        .HasForeignKey("PodcastEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.GenreSerie", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.Serie")
                        .WithMany("Genres")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieEpisode", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.Serie", "Serie")
                        .WithMany("Episode")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.SerieRatingReview", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.SerieEpisode")
                        .WithMany("RatingReviews")
                        .HasForeignKey("SerieEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSerieFavourite", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.SerieEpisode")
                        .WithMany("Favourites")
                        .HasForeignKey("SerieEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MediaWeb.Domain.Serie.UserSeriePlaylist", b =>
                {
                    b.HasOne("MediaWeb.Domain.Serie.SerieEpisode")
                        .WithMany("Playlist")
                        .HasForeignKey("SerieEpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
